language: node_js

node_js:
  - "8"
  - "7"
  - "6"
  - "4"

script:
  - yarn lint
  - yarn add typescript@2.1
  - yarn ci
  - yarn add typescript@2.2
  - yarn ci
  - yarn add typescript@2.3
  - yarn ci
